name: 自动部署

on:
  push:
    branches:
      - stage

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - name: 在服务器上拉取代码
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /www/wwwroot/xhj-webview
            sudo -u www git reset --hard HEAD~1
            sudo -u www git pull